name: flutter_wanandroid
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

    #网络
  dio: ^4.0.1

    #本地key-value缓存
  shared_preferences: ^2.0.13

    #接口缓存
  dio_http_cache: ^0.3.0

    #文件路径操作
  path: ^1.8.0

  #通知
  event_bus: ^2.0.0

      #下拉刷新
  pull_to_refresh: ^2.0.0

    #json库
  json_annotation: ^4.1.0

    #图片缓存
  cached_network_image: ^3.2.0

    #图片浏览
  photo_view: ^0.13.0

  fish_redux: ^0.3.7

  encrypt: ^5.0.0

    #卡片切换
  card_swiper: ^1.0.4

  html_unescape: ^2.0.0

  #webview
  webview_flutter: ^3.0.4

  #拖动组件
  reorderables: ^0.4.0

  #左滑删除
  flutter_slidable: 1.3.0

  #sqflite
  sqflite: ^2.0.2

  # 高德地图
  amap_flutter_map: ^3.0.0

  # 定位
  amap_flutter_location: ^3.0.0

  flutter_boost:
    git:
      url: https://github.com/alibaba/flutter_boost.git
      ref: 'v3.0-null-safety-preview.18'

dev_dependencies:
  flutter_test:
    sdk: flutter
  #自动生成代码
  source_gen: ^1.1.1

  #自动生成代码
  build_runner: ^2.1.4

  #json解析
  json_serializable: ^5.0.0


dependency_overrides:
  #接口缓存，等这个库的json_serializable依赖更新到5.0再切回来
  dio_http_cache:
    git: git@github.com:uquabc/dio-http-cache.git

  flutter_boost:
    git:
      url: https://github.com/alibaba/flutter_boost.git
      ref: 'v3.0-null-safety-preview.18'

  fish_redux:
    git: git@github.com:leftcoding/fish-redux.git


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    #字体图标
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

